backend:
  name: git-gateway

local_backend: true

publish_mode: editorial_workflow
media_folder: "web-app/public/images"
public_folder: "/images"

collections:
  - name: "project"
    label: "Project"
    folder: "data/projects"
    create: true
    format: "json"
    identifier_field: id
    summary: "{{name}}"
    fields:
      - { label: "id", name: "id", widget: "uuid" }
      - { label: "name", name: "name", widget: "string" }
      - {
          label: "Customer",
          name: "customer",
          widget: "relation",
          collection: "company",
          value_field: "id",
          search_fields: ["name"],
          display_fields: ["name"],
        }
      - { label: "Business goal", name: "business_goal", widget: "markdown" }
  - name: "company"
    label: "Company"
    folder: "data/companies"
    create: true
    format: "json"
    identifier_field: id
    summary: "{{name}}"
    fields:
      - { label: "id", name: "id", widget: "uuid" }
      - { label: "name", name: "name", widget: "string" }
